import Database from '@tauri-apps/plugin-sql';
import { invoke } from '@tauri-apps/api/core';

let _db: Database | null = null;
let _currentProfileId: string | null = null;

/**
 * Returns the active SQLite database connection.
 * Throws if no profile has been loaded yet — call loadProfileDB() first.
 */
export function getDB(): Database {
  if (!_db) {
    throw new Error(
      '[db] No database loaded. Call loadProfileDB(profileId) before accessing the DB.',
    );
  }
  return _db;
}

/**
 * Load (or switch to) the SQLite database for a specific profile.
 * - Creates the profile folder on disk if it doesn't exist.
 * - Opens `profiles/<uuid>/data.sqlite` via the Tauri SQL plugin.
 * - Runs Drizzle-style migrations (FTS5 triggers, etc.).
 *
 * If another profile DB was open, it is closed first.
 */
export async function loadProfileDB(profileId: string): Promise<Database> {
  // Skip if already connected to this profile
  if (_db && _currentProfileId === profileId) return _db;

  // Close previous connection
  if (_db) {
    try {
      await _db.close();
    } catch {
      // Ignore close errors on stale handles
    }
    _db = null;
    _currentProfileId = null;
  }

  // Ensure the profile directory exists on disk — returns the absolute path
  const profilePath = await invoke<string>('create_profile_folder', { uuid: profileId });

  // Open the profile-specific SQLite database using the absolute path
  // (relative paths resolve to app config dir, not app data dir on Linux)
  _db = await Database.load(`sqlite:${profilePath}/data.sqlite`);
  _currentProfileId = profileId;

  // Run schema migrations
  await runMigrations(_db);

  console.log(`[db] Profile DB loaded: ${profileId}`);
  return _db;
}

/**
 * Close the current profile database (e.g. before switching profiles).
 */
export async function closeProfileDB(): Promise<void> {
  if (_db) {
    await _db.close();
    _db = null;
    _currentProfileId = null;
  }
}

/**
 * Returns the profile ID of the currently loaded database (or null).
 */
export function getCurrentProfileId(): string | null {
  return _currentProfileId;
}

// ── Migrations ────────────────────────────────────────────────────────────────

// Drizzle-generated migration SQL (from drizzle/0000_init.sql)
// We inline it so the Tauri app carries no extra FS reads at runtime.
const DRIZZLE_MIGRATION_0000 = `
CREATE TABLE IF NOT EXISTS \`active_tools\` (
  \`profile_id\` text NOT NULL,
  \`tool_id\` text NOT NULL,
  \`is_enabled\` integer DEFAULT 1 NOT NULL
);
CREATE TABLE IF NOT EXISTS \`base_entities\` (
  \`id\` text PRIMARY KEY NOT NULL,
  \`type\` text NOT NULL,
  \`payload\` text DEFAULT '{}' NOT NULL,
  \`metadata\` text DEFAULT '{}' NOT NULL,
  \`tags\` text DEFAULT '[]' NOT NULL,
  \`parent_id\` text,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  \`deleted_at\` text
);
CREATE TABLE IF NOT EXISTS \`local_files\` (
  \`hash\` text PRIMARY KEY NOT NULL,
  \`local_path\` text NOT NULL,
  \`mime_type\` text DEFAULT 'application/octet-stream' NOT NULL,
  \`size_bytes\` integer NOT NULL,
  \`reference_count\` integer DEFAULT 1 NOT NULL,
  \`created_at\` text NOT NULL
);
`;

/**
 * Run Drizzle-generated + custom FTS5 migrations.
 * All statements are idempotent (IF NOT EXISTS).
 */
async function runMigrations(db: Database): Promise<void> {
  // ── 1. Drizzle-generated tables ────────────────────────────────────────────
  const statements = DRIZZLE_MIGRATION_0000
    .split(';')
    .map((s) => s.trim())
    .filter(Boolean);

  for (const stmt of statements) {
    await db.execute(stmt);
  }

  // ── 2. Indexes (not generated by Drizzle for SQLite) ───────────────────────
  await db.execute(`CREATE INDEX IF NOT EXISTS idx_base_entities_type ON base_entities(type);`);
  await db.execute(`CREATE INDEX IF NOT EXISTS idx_base_entities_parent ON base_entities(parent_id);`);
  await db.execute(`CREATE INDEX IF NOT EXISTS idx_base_entities_deleted ON base_entities(deleted_at);`);

  // ── 3. FTS5 virtual table (Drizzle cannot generate these) ──────────────────
  await db.execute(`
    CREATE VIRTUAL TABLE IF NOT EXISTS base_entities_fts
    USING fts5(
      id UNINDEXED,
      type,
      payload,
      tags,
      content='base_entities',
      content_rowid='rowid'
    );
  `);

  // Triggers to keep FTS in sync with the main table
  await db.execute(`
    CREATE TRIGGER IF NOT EXISTS base_entities_ai
    AFTER INSERT ON base_entities BEGIN
      INSERT INTO base_entities_fts(rowid, id, type, payload, tags)
      VALUES (new.rowid, new.id, new.type, new.payload, new.tags);
    END;
  `);

  await db.execute(`
    CREATE TRIGGER IF NOT EXISTS base_entities_ad
    AFTER DELETE ON base_entities BEGIN
      INSERT INTO base_entities_fts(base_entities_fts, rowid, id, type, payload, tags)
      VALUES ('delete', old.rowid, old.id, old.type, old.payload, old.tags);
    END;
  `);

  await db.execute(`
    CREATE TRIGGER IF NOT EXISTS base_entities_au
    AFTER UPDATE ON base_entities BEGIN
      INSERT INTO base_entities_fts(base_entities_fts, rowid, id, type, payload, tags)
      VALUES ('delete', old.rowid, old.id, old.type, old.payload, old.tags);
      INSERT INTO base_entities_fts(rowid, id, type, payload, tags)
      VALUES (new.rowid, new.id, new.type, new.payload, new.tags);
    END;
  `);

  console.log('[db] Migrations complete');
}

/**
 * Perform an FTS5 full-text search across all base_entities.
 * Returns matching entity IDs ordered by rank.
 */
export async function ftsSearch(query: string): Promise<string[]> {
  const db = getDB();
  // Sanitise: escape double-quotes, wrap in FTS5 phrase
  const safe = query.replace(/"/g, '""');
  const rows = await db.select<{ id: string }[]>(
    `SELECT id FROM base_entities_fts WHERE base_entities_fts MATCH ? ORDER BY rank LIMIT 50`,
    [`"${safe}"`],
  );
  return rows.map((r) => r.id);
}
